In [ ]:
!pip install google-play-scraper pandas

Requirement already satisfied: google-play-scraper in /usr/local/lib/python3.12/dist-packages (1.2.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
!git clone https://github.com/edent4313-star/fintech-review-analytics.git

Cloning into 'fintech-review-analytics'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 19 (delta 1), reused 16 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (19/19), done.
Resolving deltas: 100% (1/1), done.

In [ ]:
%cd fintech-review-analytics

/content/fintech-review-analytics

In [ ]:
!git checkout Task-1

Branch 'Task-1' set up to track remote branch 'Task-1' from 'origin'.
Switched to a new branch 'Task-1'

In [ ]:
!git config --global user.name "edent4313-star"
!git config --global user.email "edent4313@gmail.com"

In [ ]:
!git add .
!git commit -m "TASK-1"

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

In [ ]:
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

Everything up-to-date

In [ ]:
# Core libraries
import pandas as pd
import numpy as np
import re
from datetime import datetime

from google_play_scraper import app, reviews, Sort

print("Libraries loaded successfully!")

Libraries loaded successfully!

**CBE**


## Part 1 — Web Scraping

In [ ]:
# The unique identifier for CBE Bank's app on the Google Play Store
CBE_APP_ID = "com.combanketh.mobilebanking"

# Step 1: Get app metadata (rating, installs, description...)
app_info = app(
    CBE_APP_ID,
    lang='en',    # Language: English
    country='et'  # Country: Ethiopia
)

print("=" * 50)
print("CBE Bank App Info")
print("=" * 50)
print(f"App Title   : {app_info['title']}")
print(f"Current Score: {app_info['score']}")
print(f"Total Ratings: {app_info['ratings']:,}")
print(f"Total Reviews: {app_info['reviews']:,}")
print(f"Installs     : {app_info['installs']}")

==================================================
CBE Bank App Info
==================================================
App Title   : Commercial Bank of Ethiopia
Current Score: 4.2869453
Total Ratings: 48,305
Total Reviews: 9,309
Installs     : 5,000,000+

In [ ]:
!git add .
!git commit -m "Web Scraping CBE"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean
Everything up-to-date


## Part 2 — Scraping Reviews

In [ ]:
# Step 2: Scrape reviews
print(f"Scraping reviews for CBE Bank...")

result, continuation_token = reviews(
    CBE_APP_ID,
    lang='en',
    country='et',
    sort=Sort.NEWEST,
    count=400,
    filter_score_with=None
)

print(f"Collected {len(result)} raw reviews")

Scraping reviews for CBE Bank...
Collected 400 raw reviews

In [ ]:
print("Keys in a single review:")
print(list(result[0].keys()))

print("\nFirst raw review (sample):")
for key, value in result[0].items():
    print(f"  {key}: {value}")

Keys in a single review:
['reviewId', 'userName', 'userImage', 'content', 'score', 'thumbsUpCount', 'reviewCreatedVersion', 'at', 'replyContent', 'repliedAt', 'appVersion']

First raw review (sample):
  reviewId: 06f6640c-b65c-43e4-88ef-0a79be8b9534
  userName: Abdi Lc
  userImage: https://play-lh.googleusercontent.com/a-/ALV-UjVVNd4xFs9wCfPd0n91qzJemrsPN5ldS_wGPSIRJtPISU5GgNbR
  content: it's a good application
  score: 5
  thumbsUpCount: 0
  reviewCreatedVersion: 5.3.0
  at: 2026-05-13 17:28:58
  replyContent: None
  repliedAt: None
  appVersion: 5.3.0

In [ ]:
raw_data = []

for r in result:
    raw_data.append({
        'review_id': r.get('reviewId', ''),
        'review'   : r.get('content', ''),
        'rating'   : r.get('score', None),
        'date'     : r.get('at', None),
        'bank'     : 'CBE Bank',
        'source'   : 'Google Play'
    })

# Build a DataFrame
df_raw = pd.DataFrame(raw_data)

print(f"Shape: {df_raw.shape}")
df_raw.head()

Shape: (400, 6)

,review_id,review,rating,date,bank,source
0,06f6640c-b65c-43e4-88ef-0a79be8b9534,it's a good application,5,2026-05-13 17:28:58,CBE Bank,Google Play
1,eda74236-f7f3-4422-a139-a181e832bc27,thank you cbe,5,2026-05-13 14:16:37,CBE Bank,Google Play
2,ff53332b-2e76-46d6-83d3-f93f968a4b18,is good,5,2026-05-13 13:18:45,CBE Bank,Google Play
3,363a5616-ed3d-4274-85ee-77071067f81d,wow,5,2026-05-13 09:19:17,CBE Bank,Google Play
4,56185597-d29b-4a60-a0fb-6783638230a7,Good application,2,2026-05-13 08:27:52,CBE Bank,Google Play

In [ ]:
!git add .
!git commit -m "Scraping Reviews CBE"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean
Everything up-to-date


## Part 3 — Exploring the Raw Data

In [ ]:
print(f"Total reviews collected: {len(df_raw)}")
print(f"\nColumn dtypes:")
print(df_raw.dtypes)

Total reviews collected: 400

Column dtypes:
review_id            object
review               object
rating                int64
date         datetime64[ns]
bank                 object
source               object
dtype: object

In [ ]:
print("Rating distribution:")
rating_counts = df_raw['rating'].value_counts().sort_index(ascending=False)
for rating, count in rating_counts.items():
    bar = '█' * (count // 5)
    print(f"  {int(rating)} stars: {count:>4}  {bar}")

Rating distribution:
  5 stars:  277  ███████████████████████████████████████████████████████
  4 stars:   31  ██████
  3 stars:   27  █████
  2 stars:    7  █
  1 stars:   58  ███████████

In [ ]:
print("Sample date values (raw):")
print(df_raw['date'].head(10).to_string())

print(f"\nDate dtype: {df_raw['date'].dtype}")

Sample date values (raw):
0   2026-05-13 17:28:58
1   2026-05-13 14:16:37
2   2026-05-13 13:18:45
3   2026-05-13 09:19:17
4   2026-05-13 08:27:52
5   2026-05-13 08:21:48
6   2026-05-13 08:11:25
7   2026-05-13 02:12:17
8   2026-05-12 16:02:00
9   2026-05-12 09:23:58

Date dtype: datetime64[ns]

In [ ]:
!git add .
!git commit -m "Exploring the Raw Data CBE"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean
Everything up-to-date


## Part 4 — Data Quality Audit

In [ ]:
print("=" * 50)
print("DATA QUALITY AUDIT")
print("=" * 50)

# --- Problem 1: Missing Values ---
print("\nProblem 1: Missing Values")
print("-" * 30)
missing = df_raw.isnull().sum()
missing_pct = (missing / len(df_raw) * 100).round(2)

for col in df_raw.columns:
    status = f"{missing[col]} missing ({missing_pct[col]}%)" if missing[col] > 0 else "OK"
    print(f"  {col:<15}: {status}")

==================================================
DATA QUALITY AUDIT
==================================================

Problem 1: Missing Values
------------------------------
  review_id      : OK
  review         : OK
  rating         : OK
  date           : OK
  bank           : OK
  source         : OK

In [ ]:
print("Problem 2: Duplicates")
print("-" * 30)

# Exact duplicates on review text
exact_dupes = df_raw.duplicated(subset=['review']).sum()
print(f"  Exact duplicate reviews : {exact_dupes}")

# Duplicate review IDs
id_dupes = df_raw.duplicated(subset=['review_id']).sum()
print(f"  Duplicate review IDs    : {id_dupes}")

# Empty reviews (also a form of bad data)
empty_reviews = (df_raw['review'].str.strip() == '').sum()
print(f"  Empty review texts      : {empty_reviews}")

Problem 2: Duplicates
------------------------------
  Exact duplicate reviews : 105
  Duplicate review IDs    : 0
  Empty review texts      : 0

In [ ]:
# --- Problem 3: Date Format ---
print("Problem 3: Date Format")
print("-" * 30)
print(f"  Current dtype: {df_raw['date'].dtype}")
print(f"  Sample values: {df_raw['date'].iloc[0]}")
print(f"  Target format: YYYY-MM-DD (string or date object)")

Problem 3: Date Format
------------------------------
  Current dtype: datetime64[ns]
  Sample values: 2026-05-13 17:28:58
  Target format: YYYY-MM-DD (string or date object)

In [ ]:
!git add .
!git commit -m "Data Quality Audit CBE"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean
Everything up-to-date


## Part 5 — Cleaning Strategy

In [ ]:
df = df_raw.copy()

print(f"Starting with: {len(df)} reviews")

Starting with: 400 reviews

In [ ]:
before = len(df)

# Drop rows missing the critical columns
critical_cols = ['review', 'rating']
df = df.dropna(subset=critical_cols)

removed = before - len(df)
print(f"Removed {removed} rows with missing critical data")
print(f"Remaining: {len(df)} reviews")

Removed 0 rows with missing critical data
Remaining: 400 reviews

In [ ]:
before = len(df)

df = df.drop_duplicates(subset=['review_id'], keep='first')

removed = before - len(df)
print(f"Removed {removed} duplicate reviews")
print(f"Remaining: {len(df)} reviews")

Removed 0 duplicate reviews
Remaining: 400 reviews

In [ ]:
print("Before normalization:")
print(df['date'].head(3).to_string())
print(f"dtype: {df['date'].dtype}")

# Convert to pandas datetime, then format as YYYY-MM-DD string
df['date'] = pd.to_datetime(df['date']).dt.strftime('%Y-%m-%d')

print("\nAfter normalization:")
print(df['date'].head(3).to_string())
print(f"dtype: {df['date'].dtype}")

print(f"\nDate range: {df['date'].min()} to {df['date'].max()}")

Before normalization:
0   2026-05-13 17:28:58
1   2026-05-13 14:16:37
2   2026-05-13 13:18:45
dtype: datetime64[ns]

After normalization:
0    2026-05-13
1    2026-05-13
2    2026-05-13
dtype: object

Date range: 2026-03-19 to 2026-05-13

In [ ]:
def clean_text(text):
    """Standardize review text: collapse whitespace, strip edges."""
    if pd.isna(text):
        return ''
    text = str(text)
    text = re.sub(r'\s+', ' ', text)  # collapse multiple spaces/newlines
    text = text.strip()               # remove leading/trailing whitespace
    return text

# Show before/after on a sample review
sample_raw = "  Great   app!\n\nVery useful.  "
print(f"Before: {repr(sample_raw)}")
print(f"After : {repr(clean_text(sample_raw))}")

# Apply to the full column
df['review'] = df['review'].apply(clean_text)

# Remove any reviews that became empty after cleaning
before = len(df)
df = df[df['review'].str.len() > 0]
removed = before - len(df)
print(f"\nRemoved {removed} reviews that were empty after cleaning")

Before: '  Great   app!\n\nVery useful.  '
After : 'Great app! Very useful.'

Removed 0 reviews that were empty after cleaning

In [ ]:
# Check for out-of-range ratings
invalid_ratings = df[(df['rating'] < 1) | (df['rating'] > 5)]
print(f"Invalid ratings (outside 1–5): {len(invalid_ratings)}")

# Remove them
df = df[(df['rating'] >= 1) & (df['rating'] <= 5)]

# Ensure rating is stored as integer
df['rating'] = df['rating'].astype(int)

print(f"Remaining: {len(df)} reviews")
print(f"Rating dtype: {df['rating'].dtype}")

Invalid ratings (outside 1–5): 0
Remaining: 400 reviews
Rating dtype: int64

In [ ]:
!git add .
!git commit -m "Cleaning Strategy CBE"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean
Everything up-to-date


## Part 6 — Final Output

In [ ]:
# Select only the 5 required columns in the right order
df_clean = df[['review', 'rating', 'date', 'bank', 'source']].copy()

# Sort by date (newest first) for clean presentation
df_clean = df_clean.sort_values('date', ascending=False).reset_index(drop=True)

print(f"Final dataset shape: {df_clean.shape}")
df_clean.head(10)

Final dataset shape: (400, 5)

,review,rating,date,bank,source
0,it's a good application,5,2026-05-13,CBE Bank,Google Play
1,is good,5,2026-05-13,CBE Bank,Google Play
2,wow,5,2026-05-13,CBE Bank,Google Play
3,Good application,2,2026-05-13,CBE Bank,Google Play
4,"Nice, but I can't get some recently transactio...",5,2026-05-13,CBE Bank,Google Play
5,Very Secure but very poor interface and limite...,1,2026-05-13,CBE Bank,Google Play
6,very nice 100%,5,2026-05-13,CBE Bank,Google Play
7,thank you cbe,5,2026-05-13,CBE Bank,Google Play
8,good,5,2026-05-12,CBE Bank,Google Play
9,Good to use,5,2026-05-12,CBE Bank,Google Play

In [ ]:
# Save to CSV
import os
os.makedirs('data/processed', exist_ok=True)

output_path = 'data/processed/CBE_bank_reviews_clean.csv'
df_clean.to_csv(output_path, index=False)

print(f"Saved to: {output_path}")

Saved to: data/processed/CBE_bank_reviews_clean.csv

In [ ]:
!git add .
!git commit -m "Final Output CBE"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean
Everything up-to-date


## Part 7 — Preprocessing Report

In [ ]:
print("=" * 55)
print("  PREPROCESSING REPORT — CBE Bank Reviews")
print("=" * 55)

original_count = len(df_raw)
final_count    = len(df_clean)
removed_total  = original_count - final_count
retention_rate = (final_count / original_count * 100)

print(f"\n  Raw reviews collected  : {original_count:>6}")
print(f"  Reviews after cleaning : {final_count:>6}")
print(f"  Reviews removed        : {removed_total:>6}")
print(f"  Data retention rate    : {retention_rate:>5.1f}%")

quality = "EXCELLENT" if retention_rate >= 95 else ("GOOD" if retention_rate >= 90 else "NEEDS ATTENTION")
print(f"  Data quality           : {quality}")

print(f"\n  Date range : {df_clean['date'].min()}  to  {df_clean['date'].max()}")

print("\n  Rating distribution:")
for rating in sorted(df_clean['rating'].unique(), reverse=True):
    count = (df_clean['rating'] == rating).sum()
    pct   = count / final_count * 100
    bar   = '█' * (count // 5)
    print(f"    {rating} stars : {count:>4} ({pct:4.1f}%)  {bar}")

print("\n  Text length stats:")
lengths = df_clean['review'].str.len()
print(f"    Min    : {lengths.min()} characters")
print(f"    Median : {lengths.median():.0f} characters")
print(f"    Max    : {lengths.max()} characters")

print("\n  Columns in final CSV:")
for col in df_clean.columns:
    print(f"    - {col}")

print("\n" + "=" * 55)

=======================================================
  PREPROCESSING REPORT — CBE Bank Reviews
=======================================================

  Raw reviews collected  :    400
  Reviews after cleaning :    400
  Reviews removed        :      0
  Data retention rate    : 100.0%
  Data quality           : EXCELLENT

  Date range : 2026-03-19  to  2026-05-13

  Rating distribution:
    5 stars :  277 (69.2%)  ███████████████████████████████████████████████████████
    4 stars :   31 ( 7.8%)  ██████
    3 stars :   27 ( 6.8%)  █████
    2 stars :    7 ( 1.8%)  █
    1 stars :   58 (14.5%)  ███████████

  Text length stats:
    Min    : 1 characters
    Median : 13 characters
    Max    : 482 characters

  Columns in final CSV:
    - review
    - rating
    - date
    - bank
    - source

=======================================================

**DASHEN**


## Part 1 — Web Scraping

In [ ]:
# The unique identifier for  DASHEN Bank's app on the Google Play Store
Dashen_APP_ID = "com.dashen.dashensuperapp"

# Step 1: Get app metadata (rating, installs, description...)
app_info = app(
    Dashen_APP_ID,
    lang='en',    # Language: English
    country='et'  # Country: Ethiopia
)

print("=" * 50)
print("DASHEN Bank App Info")
print("=" * 50)
print(f"App Title   : {app_info['title']}")
print(f"Current Score: {app_info['score']}")
print(f"Total Ratings: {app_info['ratings']:,}")
print(f"Total Reviews: {app_info['reviews']:,}")
print(f"Installs     : {app_info['installs']}")

==================================================
DASHEN Bank App Info
==================================================
App Title   : Dashen Bank
Current Score: 4.221631
Total Ratings: 5,610
Total Reviews: 1,025
Installs     : 1,000,000+

In [ ]:
!git add .
!git commit -m "Web Scraping DASHEN"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean
Everything up-to-date


## Part 2 — Scraping Reviews

In [ ]:
# Step 2: Scrape reviews
print(f"Scraping reviews for DASHEN Bank...")

result, continuation_token = reviews(
    Dashen_APP_ID,
    lang='en',
    country='et',
    sort=Sort.NEWEST,       # Most recent first
    count=400,              # Ask for more than 400 to be safe
    filter_score_with=None  # All star ratings
)

print(f"Collected {len(result)} raw reviews")

Scraping reviews for DASHEN Bank...
Collected 400 raw reviews

In [ ]:
print("Keys in a single review:")
print(list(result[0].keys()))

print("\nFirst raw review (sample):")
for key, value in result[0].items():
    print(f"  {key}: {value}")

Keys in a single review:
['reviewId', 'userName', 'userImage', 'content', 'score', 'thumbsUpCount', 'reviewCreatedVersion', 'at', 'replyContent', 'repliedAt', 'appVersion']

First raw review (sample):
  reviewId: dfcafbd5-be84-4c83-814f-301c05e35491
  userName: Balisaa iliyaas
  userImage: https://play-lh.googleusercontent.com/a-/ALV-UjWeIqYmtBixP28iuYneth66ttD-o-TE54SQT6QSP9FGnXGm3ok
  content: bas
  score: 5
  thumbsUpCount: 0
  reviewCreatedVersion: None
  at: 2026-05-13 17:58:19
  replyContent: None
  repliedAt: None
  appVersion: None

In [ ]:
raw_data = []

for r in result:
    raw_data.append({
        'review_id': r.get('reviewId', ''),
        'review'   : r.get('content', ''),
        'rating'   : r.get('score', None),
        'date'     : r.get('at', None),
        'bank'     : 'Dashen Bank',
        'source'   : 'Google Play'
    })

# Build a DataFrame
df_raw = pd.DataFrame(raw_data)

print(f"Shape: {df_raw.shape}")
df_raw.head()

Shape: (400, 6)

,review_id,review,rating,date,bank,source
0,dfcafbd5-be84-4c83-814f-301c05e35491,bas,5,2026-05-13 17:58:19,Dashen Bank,Google Play
1,abf6804b-429f-4383-94a1-5a5955c27569,bad mobile banking at all,1,2026-05-13 16:14:11,Dashen Bank,Google Play
2,265cfda4-296c-4676-bc76-032559a65ec2,very nice app.,5,2026-05-13 14:44:57,Dashen Bank,Google Play
3,94a4413f-40c7-4842-b31c-43f70aff0686,very difficult app,1,2026-05-13 13:26:31,Dashen Bank,Google Play
4,eaeb3ab3-2f40-49c2-be8f-8d434331b7cb,"Good app, but debit transactions not allowed W...",5,2026-05-13 08:41:27,Dashen Bank,Google Play

In [ ]:
!git add .
!git commit -m "Scraping Reviews DASHEN"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean
Everything up-to-date


## Part 3 — Exploring the Raw Data

In [ ]:
# Basic shape and types
print(f"Total reviews collected: {len(df_raw)}")
print(f"\nColumn dtypes:")
print(df_raw.dtypes)

Total reviews collected: 400

Column dtypes:
review_id            object
review               object
rating                int64
date         datetime64[ns]
bank                 object
source               object
dtype: object

In [ ]:
print("Rating distribution:")
rating_counts = df_raw['rating'].value_counts().sort_index(ascending=False)
for rating, count in rating_counts.items():
    bar = '█' * (count // 5)
    print(f"  {int(rating)} stars: {count:>4}  {bar}")

Rating distribution:
  5 stars:  264  ████████████████████████████████████████████████████
  4 stars:   27  █████
  3 stars:   19  ███
  2 stars:   13  ██
  1 stars:   77  ███████████████

In [ ]:
print("Sample date values (raw):")
print(df_raw['date'].head(10).to_string())

print(f"\nDate dtype: {df_raw['date'].dtype}")

Sample date values (raw):
0   2026-05-13 17:58:19
1   2026-05-13 16:14:11
2   2026-05-13 14:44:57
3   2026-05-13 13:26:31
4   2026-05-13 08:41:27
5   2026-05-13 05:15:58
6   2026-05-12 14:33:07
7   2026-05-12 14:22:54
8   2026-05-12 13:43:12
9   2026-05-12 11:56:04

Date dtype: datetime64[ns]

In [ ]:
!git add .
!git commit -m "Exploring the Raw Data DASHEN"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean
Everything up-to-date


## Part 4 — Data Quality Audit

In [ ]:
print("=" * 50)
print("DATA QUALITY AUDIT")
print("=" * 50)

# --- Problem 1: Missing Values ---
print("\nProblem 1: Missing Values")
print("-" * 30)
missing = df_raw.isnull().sum()
missing_pct = (missing / len(df_raw) * 100).round(2)

for col in df_raw.columns:
    status = f"{missing[col]} missing ({missing_pct[col]}%)" if missing[col] > 0 else "OK"
    print(f"  {col:<15}: {status}")

==================================================
DATA QUALITY AUDIT
==================================================

Problem 1: Missing Values
------------------------------
  review_id      : OK
  review         : OK
  rating         : OK
  date           : OK
  bank           : OK
  source         : OK

In [ ]:
# --- Problem 2: Duplicate Reviews ---
print("Problem 2: Duplicates")
print("-" * 30)

# Exact duplicates on review text
exact_dupes = df_raw.duplicated(subset=['review']).sum()
print(f"  Exact duplicate reviews : {exact_dupes}")

# Duplicate review IDs
id_dupes = df_raw.duplicated(subset=['review_id']).sum()
print(f"  Duplicate review IDs    : {id_dupes}")

# Empty reviews (also a form of bad data)
empty_reviews = (df_raw['review'].str.strip() == '').sum()
print(f"  Empty review texts      : {empty_reviews}")

Problem 2: Duplicates
------------------------------
  Exact duplicate reviews : 57
  Duplicate review IDs    : 0
  Empty review texts      : 0

In [ ]:
# --- Problem 3: Date Format ---
print("Problem 3: Date Format")
print("-" * 30)
print(f"  Current dtype: {df_raw['date'].dtype}")
print(f"  Sample values: {df_raw['date'].iloc[0]}")
print(f"  Target format: YYYY-MM-DD (string or date object)")

Problem 3: Date Format
------------------------------
  Current dtype: datetime64[ns]
  Sample values: 2026-05-13 17:58:19
  Target format: YYYY-MM-DD (string or date object)

In [ ]:
!git add .
!git commit -m "Data Quality Audit DASHEN"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean
Everything up-to-date


## Part 5 — Cleaning Strategy

In [ ]:
df = df_raw.copy()

print(f"Starting with: {len(df)} reviews")

Starting with: 400 reviews

In [ ]:
before = len(df)

# Drop rows missing the critical columns
critical_cols = ['review', 'rating']
df = df.dropna(subset=critical_cols)

removed = before - len(df)
print(f"Removed {removed} rows with missing critical data")
print(f"Remaining: {len(df)} reviews")

Removed 0 rows with missing critical data
Remaining: 400 reviews

In [ ]:
before = len(df)

df = df.drop_duplicates(subset=['review_id'], keep='first')

removed = before - len(df)
print(f"Removed {removed} duplicate reviews")
print(f"Remaining: {len(df)} reviews")

Removed 0 duplicate reviews
Remaining: 400 reviews

In [ ]:
print("Before normalization:")
print(df['date'].head(3).to_string())
print(f"dtype: {df['date'].dtype}")

# Convert to pandas datetime, then format as YYYY-MM-DD string
df['date'] = pd.to_datetime(df['date']).dt.strftime('%Y-%m-%d')

print("\nAfter normalization:")
print(df['date'].head(3).to_string())
print(f"dtype: {df['date'].dtype}")

print(f"\nDate range: {df['date'].min()} to {df['date'].max()}")

Before normalization:
0   2026-05-13 17:58:19
1   2026-05-13 16:14:11
2   2026-05-13 14:44:57
dtype: datetime64[ns]

After normalization:
0    2026-05-13
1    2026-05-13
2    2026-05-13
dtype: object

Date range: 2025-09-28 to 2026-05-13

In [ ]:
def clean_text(text):
    """Standardize review text: collapse whitespace, strip edges."""
    if pd.isna(text):
        return ''
    text = str(text)
    text = re.sub(r'\s+', ' ', text)  # collapse multiple spaces/newlines
    text = text.strip()               # remove leading/trailing whitespace
    return text

# Show before/after on a sample review
sample_raw = "  Great   app!\n\nVery useful.  "
print(f"Before: {repr(sample_raw)}")
print(f"After : {repr(clean_text(sample_raw))}")

# Apply to the full column
df['review'] = df['review'].apply(clean_text)

# Remove any reviews that became empty after cleaning
before = len(df)
df = df[df['review'].str.len() > 0]
removed = before - len(df)
print(f"\nRemoved {removed} reviews that were empty after cleaning")

Before: '  Great   app!\n\nVery useful.  '
After : 'Great app! Very useful.'

Removed 0 reviews that were empty after cleaning

In [ ]:
# Check for out-of-range ratings
invalid_ratings = df[(df['rating'] < 1) | (df['rating'] > 5)]
print(f"Invalid ratings (outside 1–5): {len(invalid_ratings)}")

# Remove them
df = df[(df['rating'] >= 1) & (df['rating'] <= 5)]

# Ensure rating is stored as integer
df['rating'] = df['rating'].astype(int)

print(f"Remaining: {len(df)} reviews")
print(f"Rating dtype: {df['rating'].dtype}")

Invalid ratings (outside 1–5): 0
Remaining: 400 reviews
Rating dtype: int64

In [ ]:
!git add .
!git commit -m "Cleaning Strategy DASHEN"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean
Everything up-to-date


## Part 6 — Final Output

In [ ]:
# Select only the 5 required columns in the right order
df_clean = df[['review', 'rating', 'date', 'bank', 'source']].copy()

# Sort by date (newest first) for clean presentation
df_clean = df_clean.sort_values('date', ascending=False).reset_index(drop=True)

print(f"Final dataset shape: {df_clean.shape}")
df_clean.head(10)

Final dataset shape: (400, 5)

,review,rating,date,bank,source
0,bas,5,2026-05-13,Dashen Bank,Google Play
1,"Good app, but debit transactions not allowed W...",5,2026-05-13,Dashen Bank,Google Play
2,nice,5,2026-05-13,Dashen Bank,Google Play
3,bad mobile banking at all,1,2026-05-13,Dashen Bank,Google Play
4,very difficult app,1,2026-05-13,Dashen Bank,Google Play
5,very nice app.,5,2026-05-13,Dashen Bank,Google Play
6,Very bad customer service line. they won't pic...,1,2026-05-12,Dashen Bank,Google Play
7,smart app,5,2026-05-12,Dashen Bank,Google Play
8,The application booting time is so bad..,3,2026-05-12,Dashen Bank,Google Play
9,good,5,2026-05-12,Dashen Bank,Google Play

In [ ]:
# Save to CSV
import os
os.makedirs('data/processed', exist_ok=True)

output_path = 'data/processed/Dashen_bank_reviews_clean.csv'
df_clean.to_csv(output_path, index=False)

print(f"Saved to: {output_path}")

Saved to: data/processed/Dashen_bank_reviews_clean.csv

In [ ]:
!git add .
!git commit -m "Final Output"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean
Everything up-to-date


## Part 7 — Preprocessing Report

In [ ]:
print("=" * 55)
print("  PREPROCESSING REPORT — Dashen Bank Reviews")
print("=" * 55)

original_count = len(df_raw)
final_count    = len(df_clean)
removed_total  = original_count - final_count
retention_rate = (final_count / original_count * 100)

print(f"\n  Raw reviews collected  : {original_count:>6}")
print(f"  Reviews after cleaning : {final_count:>6}")
print(f"  Reviews removed        : {removed_total:>6}")
print(f"  Data retention rate    : {retention_rate:>5.1f}%")

quality = "EXCELLENT" if retention_rate >= 95 else ("GOOD" if retention_rate >= 90 else "NEEDS ATTENTION")
print(f"  Data quality           : {quality}")

print(f"\n  Date range : {df_clean['date'].min()}  to  {df_clean['date'].max()}")

print("\n  Rating distribution:")
for rating in sorted(df_clean['rating'].unique(), reverse=True):
    count = (df_clean['rating'] == rating).sum()
    pct   = count / final_count * 100
    bar   = '█' * (count // 5)
    print(f"    {rating} stars : {count:>4} ({pct:4.1f}%)  {bar}")

print("\n  Text length stats:")
lengths = df_clean['review'].str.len()
print(f"    Min    : {lengths.min()} characters")
print(f"    Median : {lengths.median():.0f} characters")
print(f"    Max    : {lengths.max()} characters")

print("\n  Columns in final CSV:")
for col in df_clean.columns:
    print(f"    - {col}")

print("\n" + "=" * 55)

=======================================================
  PREPROCESSING REPORT — Dashen Bank Reviews
=======================================================

  Raw reviews collected  :    400
  Reviews after cleaning :    400
  Reviews removed        :      0
  Data retention rate    : 100.0%
  Data quality           : EXCELLENT

  Date range : 2025-09-28  to  2026-05-13

  Rating distribution:
    5 stars :  264 (66.0%)  ████████████████████████████████████████████████████
    4 stars :   27 ( 6.8%)  █████
    3 stars :   19 ( 4.8%)  ███
    2 stars :   13 ( 3.2%)  ██
    1 stars :   77 (19.2%)  ███████████████

  Text length stats:
    Min    : 1 characters
    Median : 22 characters
    Max    : 498 characters

  Columns in final CSV:
    - review
    - rating
    - date
    - bank
    - source

=======================================================

**BOA**


## Part 1 — Web Scraping

In [ ]:
# The unique identifier for BOA Bank's app on the Google Play Store
BOA_APP_ID = "com.boa.boaMobileBanking"

# Step 1: Get app metadata (rating, installs, description...)
app_info = app(
    BOA_APP_ID,
    lang='en',    # Language: English
    country='et'  # Country: Ethiopia
)

print("=" * 50)
print("Awash Bank App Info")
print("=" * 50)
print(f"App Title   : {app_info['title']}")
print(f"Current Score: {app_info['score']}")
print(f"Total Ratings: {app_info['ratings']:,}")
print(f"Total Reviews: {app_info['reviews']:,}")
print(f"Installs     : {app_info['installs']}")

==================================================
Awash Bank App Info
==================================================
App Title   : BoA Mobile
Current Score: 4.3909855
Total Ratings: 9,215
Total Reviews: 1,459
Installs     : 1,000,000+

In [ ]:
!git add .
!git commit -m " Web Scraping BOA"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean
Everything up-to-date


## Part 2 — Scraping Reviews

In [ ]:
print(f"Scraping reviews for BOA Bank...")

result, continuation_token = reviews(
    BOA_APP_ID,
    lang='en',
    country='et',
    sort=Sort.NEWEST,       # Most recent first
    count=400,              # Ask for more than 400 to be safe
    filter_score_with=None  # All star ratings
)

Scraping reviews for BOA Bank...

In [ ]:
print("Keys in a single review:")
print(list(result[0].keys()))

print("\nFirst raw review (sample):")
for key, value in result[0].items():
    print(f"  {key}: {value}")

Keys in a single review:
['reviewId', 'userName', 'userImage', 'content', 'score', 'thumbsUpCount', 'reviewCreatedVersion', 'at', 'replyContent', 'repliedAt', 'appVersion']

First raw review (sample):
  reviewId: c3bb042c-844b-4580-98b9-df418622b2fb
  userName: Hamid Abdella
  userImage: https://play-lh.googleusercontent.com/a/ACg8ocKxYO7gSAW0PgoFvwbHi4RxuoH8jHuTKOA20Pv-CtODfkn93w=mo
  content: it's very good app
  score: 5
  thumbsUpCount: 0
  reviewCreatedVersion: None
  at: 2026-05-12 08:50:32
  replyContent: None
  repliedAt: None
  appVersion: None

In [ ]:
raw_data = []

for r in result:
    raw_data.append({
        'review_id': r.get('reviewId', ''),
        'review'   : r.get('content', ''),
        'rating'   : r.get('score', None),
        'date'     : r.get('at', None),
        'bank'     : 'BOA Bank',
        'source'   : 'Google Play'
    })

# Build a DataFrame
df_raw = pd.DataFrame(raw_data)

print(f"Shape: {df_raw.shape}")
df_raw.head()

Shape: (400, 6)

,review_id,review,rating,date,bank,source
0,c3bb042c-844b-4580-98b9-df418622b2fb,it's very good app,5,2026-05-12 08:50:32,BOA Bank,Google Play
1,400ce769-3726-43b2-ac4d-755b3a15f026,this app is good but the speed of app is very ...,2,2026-05-11 15:18:54,BOA Bank,Google Play
2,4d6d2f22-5e71-47be-9cde-a1cf6c9fff93,good,5,2026-05-09 11:41:50,BOA Bank,Google Play
3,e77089b3-aecf-45e2-a64a-ce917fc4233a,boa the best,5,2026-05-08 10:47:07,BOA Bank,Google Play
4,41c64c67-b81a-4326-83c4-e95044aef7f6,bank of absiniya is best bank in ethiopian,5,2026-05-07 07:33:06,BOA Bank,Google Play

In [ ]:
!git add .
!git commit -m "Scraping Reviews BOA"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean
Everything up-to-date


## Part 3 — Exploring the Raw Data

In [ ]:
print(f"Total reviews collected: {len(df_raw)}")
print(f"\nColumn dtypes:")
print(df_raw.dtypes)

Total reviews collected: 400

Column dtypes:
review_id            object
review               object
rating                int64
date         datetime64[ns]
bank                 object
source               object
dtype: object

In [ ]:
print("Rating distribution:")
rating_counts = df_raw['rating'].value_counts().sort_index(ascending=False)
for rating, count in rating_counts.items():
    bar = '█' * (count // 5)
    print(f"  {int(rating)} stars: {count:>4}  {bar}")

Rating distribution:
  5 stars:  230  ██████████████████████████████████████████████
  4 stars:   32  ██████
  3 stars:   13  ██
  2 stars:   13  ██
  1 stars:  112  ██████████████████████

In [ ]:
print("Sample date values (raw):")
print(df_raw['date'].head(10).to_string())

print(f"\nDate dtype: {df_raw['date'].dtype}")

Sample date values (raw):
0   2026-05-12 08:50:32
1   2026-05-11 15:18:54
2   2026-05-09 11:41:50
3   2026-05-08 10:47:07
4   2026-05-07 07:33:06
5   2026-05-05 08:03:08
6   2026-05-04 11:01:17
7   2026-05-03 10:40:13
8   2026-05-02 12:48:30
9   2026-05-01 06:20:45

Date dtype: datetime64[ns]

In [ ]:
!git add .
!git commit -m "Exploring the Raw Data BOA"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean
Everything up-to-date


## Part 4 — Data Quality Audit

In [ ]:
print("=" * 50)
print("DATA QUALITY AUDIT")
print("=" * 50)

# --- Problem 1: Missing Values ---
print("\nProblem 1: Missing Values")
print("-" * 30)
missing = df_raw.isnull().sum()
missing_pct = (missing / len(df_raw) * 100).round(2)

for col in df_raw.columns:
    status = f"{missing[col]} missing ({missing_pct[col]}%)" if missing[col] > 0 else "OK"
    print(f"  {col:<15}: {status}")

==================================================
DATA QUALITY AUDIT
==================================================

Problem 1: Missing Values
------------------------------
  review_id      : OK
  review         : OK
  rating         : OK
  date           : OK
  bank           : OK
  source         : OK

In [ ]:
# --- Problem 2: Duplicate Reviews ---
print("Problem 2: Duplicates")
print("-" * 30)

# Exact duplicates on review text
exact_dupes = df_raw.duplicated(subset=['review']).sum()
print(f"  Exact duplicate reviews : {exact_dupes}")

# Duplicate review IDs
id_dupes = df_raw.duplicated(subset=['review_id']).sum()
print(f"  Duplicate review IDs    : {id_dupes}")

# Empty reviews (also a form of bad data)
empty_reviews = (df_raw['review'].str.strip() == '').sum()
print(f"  Empty review texts      : {empty_reviews}")

Problem 2: Duplicates
------------------------------
  Exact duplicate reviews : 66
  Duplicate review IDs    : 0
  Empty review texts      : 0

In [ ]:

print("Problem 3: Date Format")
print("-" * 30)
print(f"  Current dtype: {df_raw['date'].dtype}")
print(f"  Sample values: {df_raw['date'].iloc[0]}")
print(f"  Target format: YYYY-MM-DD (string or date object)")

Problem 3: Date Format
------------------------------
  Current dtype: datetime64[ns]
  Sample values: 2026-05-12 08:50:32
  Target format: YYYY-MM-DD (string or date object)

In [ ]:
!git add .
!git commit -m "Data Quality Audit BOA"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean
Everything up-to-date


## Part 5 — Cleaning Strategy

In [ ]:
# Work on a copy so raw data stays untouched
df = df_raw.copy()

print(f"Starting with: {len(df)} reviews")

Starting with: 400 reviews

In [ ]:
before = len(df)

# Drop rows missing the critical columns
critical_cols = ['review', 'rating']
df = df.dropna(subset=critical_cols)

removed = before - len(df)
print(f"Removed {removed} rows with missing critical data")
print(f"Remaining: {len(df)} reviews")

Removed 0 rows with missing critical data
Remaining: 400 reviews

In [ ]:
before = len(df)

df = df.drop_duplicates(subset=['review_id'], keep='first')

removed = before - len(df)
print(f"Removed {removed} duplicate reviews")
print(f"Remaining: {len(df)} reviews")

Removed 0 duplicate reviews
Remaining: 400 reviews

In [ ]:
print("Before normalization:")
print(df['date'].head(3).to_string())
print(f"dtype: {df['date'].dtype}")

# Convert to pandas datetime, then format as YYYY-MM-DD string
df['date'] = pd.to_datetime(df['date']).dt.strftime('%Y-%m-%d')

print("\nAfter normalization:")
print(df['date'].head(3).to_string())
print(f"dtype: {df['date'].dtype}")

print(f"\nDate range: {df['date'].min()} to {df['date'].max()}")

Before normalization:
0   2026-05-12 08:50:32
1   2026-05-11 15:18:54
2   2026-05-09 11:41:50
dtype: datetime64[ns]

After normalization:
0    2026-05-12
1    2026-05-11
2    2026-05-09
dtype: object

Date range: 2025-06-13 to 2026-05-12

In [ ]:
def clean_text(text):
    """Standardize review text: collapse whitespace, strip edges."""
    if pd.isna(text):
        return ''
    text = str(text)
    text = re.sub(r'\s+', ' ', text)  # collapse multiple spaces/newlines
    text = text.strip()               # remove leading/trailing whitespace
    return text

# Show before/after on a sample review
sample_raw = "  Great   app!\n\nVery useful.  "
print(f"Before: {repr(sample_raw)}")
print(f"After : {repr(clean_text(sample_raw))}")

# Apply to the full column
df['review'] = df['review'].apply(clean_text)

# Remove any reviews that became empty after cleaning
before = len(df)
df = df[df['review'].str.len() > 0]
removed = before - len(df)
print(f"\nRemoved {removed} reviews that were empty after cleaning")

Before: '  Great   app!\n\nVery useful.  '
After : 'Great app! Very useful.'

Removed 0 reviews that were empty after cleaning

In [ ]:
# Check for out-of-range ratings
invalid_ratings = df[(df['rating'] < 1) | (df['rating'] > 5)]
print(f"Invalid ratings (outside 1–5): {len(invalid_ratings)}")

# Remove them
df = df[(df['rating'] >= 1) & (df['rating'] <= 5)]

# Ensure rating is stored as integer
df['rating'] = df['rating'].astype(int)

print(f"Remaining: {len(df)} reviews")
print(f"Rating dtype: {df['rating'].dtype}")

Invalid ratings (outside 1–5): 0
Remaining: 400 reviews
Rating dtype: int64

In [ ]:
!git add .
!git commit -m "Cleaning Strategy BOA"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean
Everything up-to-date


## Part 6 — Final Output

In [ ]:
# Select only the 5 required columns in the right order
df_clean = df[['review', 'rating', 'date', 'bank', 'source']].copy()

# Sort by date (newest first) for clean presentation
df_clean = df_clean.sort_values('date', ascending=False).reset_index(drop=True)

print(f"Final dataset shape: {df_clean.shape}")
df_clean.head(10)

Final dataset shape: (400, 5)

,review,rating,date,bank,source
0,it's very good app,5,2026-05-12,BOA Bank,Google Play
1,this app is good but the speed of app is very ...,2,2026-05-11,BOA Bank,Google Play
2,good,5,2026-05-09,BOA Bank,Google Play
3,boa the best,5,2026-05-08,BOA Bank,Google Play
4,bank of absiniya is best bank in ethiopian,5,2026-05-07,BOA Bank,Google Play
5,አስተማማኝና ዘመኑን የዋጀ,4,2026-05-05,BOA Bank,Google Play
6,good,5,2026-05-04,BOA Bank,Google Play
7,extremely slow app and unreliable for most pay...,2,2026-05-03,BOA Bank,Google Play
8,Amazing app,5,2026-05-02,BOA Bank,Google Play
9,"I tried to oppen mobile app of BOA, but it can...",1,2026-05-01,BOA Bank,Google Play

In [ ]:
# Save to CSV
import os
os.makedirs('data/processed', exist_ok=True)

output_path = 'data/processed/BOA_bank_reviews_clean.csv'
df_clean.to_csv(output_path, index=False)

print(f"Saved to: {output_path}")

Saved to: data/processed/BOA_bank_reviews_clean.csv

In [ ]:
!git add .
!git commit -m "Final Output BOA"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean
Everything up-to-date


## Part 7 — Preprocessing Report

In [ ]:
print("=" * 55)
print("  PREPROCESSING REPORT — BOA Bank Reviews")
print("=" * 55)

original_count = len(df_raw)
final_count    = len(df_clean)
removed_total  = original_count - final_count
retention_rate = (final_count / original_count * 100)

print(f"\n  Raw reviews collected  : {original_count:>6}")
print(f"  Reviews after cleaning : {final_count:>6}")
print(f"  Reviews removed        : {removed_total:>6}")
print(f"  Data retention rate    : {retention_rate:>5.1f}%")

quality = "EXCELLENT" if retention_rate >= 95 else ("GOOD" if retention_rate >= 90 else "NEEDS ATTENTION")
print(f"  Data quality           : {quality}")

print(f"\n  Date range : {df_clean['date'].min()}  to  {df_clean['date'].max()}")

print("\n  Rating distribution:")
for rating in sorted(df_clean['rating'].unique(), reverse=True):
    count = (df_clean['rating'] == rating).sum()
    pct   = count / final_count * 100
    bar   = '█' * (count // 5)
    print(f"    {rating} stars : {count:>4} ({pct:4.1f}%)  {bar}")

print("\n  Text length stats:")
lengths = df_clean['review'].str.len()
print(f"    Min    : {lengths.min()} characters")
print(f"    Median : {lengths.median():.0f} characters")
print(f"    Max    : {lengths.max()} characters")

print("\n  Columns in final CSV:")
for col in df_clean.columns:
    print(f"    - {col}")

print("\n" + "=" * 55)

=======================================================
  PREPROCESSING REPORT — BOA Bank Reviews
=======================================================

  Raw reviews collected  :    400
  Reviews after cleaning :    400
  Reviews removed        :      0
  Data retention rate    : 100.0%
  Data quality           : EXCELLENT

  Date range : 2025-06-13  to  2026-05-12

  Rating distribution:
    5 stars :  230 (57.5%)  ██████████████████████████████████████████████
    4 stars :   32 ( 8.0%)  ██████
    3 stars :   13 ( 3.2%)  ██
    2 stars :   13 ( 3.2%)  ██
    1 stars :  112 (28.0%)  ██████████████████████

  Text length stats:
    Min    : 1 characters
    Median : 14 characters
    Max    : 492 characters

  Columns in final CSV:
    - review
    - rating
    - date
    - bank
    - source

=======================================================