In [3]:
!pip install google-play-scraper pandas

Requirement already satisfied: google-play-scraper in C:\Users\habtamu.amsalu\Downloads\fintech-review-analytics\fintech-review-analytics\.venv\Lib\site-packages (1.2.7)
Requirement already satisfied: pandas in C:\Users\habtamu.amsalu\Downloads\fintech-review-analytics\fintech-review-analytics\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\habtamu.amsalu\Downloads\fintech-review-analytics\fintech-review-analytics\.venv\Lib\site-packages (from pandas) (2.4.5)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\habtamu.amsalu\Downloads\fintech-review-analytics\fintech-review-analytics\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\habtamu.amsalu\Downloads\fintech-review-analytics\fintech-review-analytics\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\habtamu.amsalu\Downloads\fintech-review-analytics\fintech-review-analytics\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
!git clone https://github.com/edent4313-star/fintech-review-analytics.git

fatal: destination path 'fintech-review-analytics' already exists and is not an empty directory.

In [5]:
%cd fintech-review-analytics

c:\Users\habtamu.amsalu\Downloads\fintech-review-analytics\fintech-review-analytics\notebooks\fintech-review-analytics

In [6]:
!git checkout Task-1

Your branch is up to date with 'origin/Task-1'.

Already on 'Task-1'

In [7]:
!git config --global user.name "edent4313-star"
!git config --global user.email "edent4313@gmail.com"

In [8]:
!git add .
!git commit -m "TASK-1"

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

In [9]:
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

Everything up-to-date

In [10]:
# Core libraries
import pandas as pd
import numpy as np
import re
from datetime import datetime

from google_play_scraper import app, reviews, Sort

print("Libraries loaded successfully!")

Libraries loaded successfully!

**CBE**


## Part 1 — Web Scraping

In [93]:
# The unique identifier for CBE Bank's app on the Google Play Store
CBE_APP_ID = "com.combanketh.mobilebanking"

# Step 1: Get app metadata (rating, installs, description...)
app_info = app(
    CBE_APP_ID,
    lang='en',    # Language: English
    country='et'  # Country: Ethiopia
)

print("=" * 50)
print("CBE Bank App Info")
print("=" * 50)
print(f"App Title   : {app_info['title']}")
print(f"Current Score: {app_info['score']}")
print(f"Total Ratings: {app_info['ratings']:,}")
print(f"Total Reviews: {app_info['reviews']:,}")
print(f"Installs     : {app_info['installs']}")

==================================================
CBE Bank App Info
==================================================
App Title   : Commercial Bank of Ethiopia
Current Score: 4.2854176
Total Ratings: 48,584
Total Reviews: 9,337
Installs     : 10,000,000+

In [12]:
!git add .
!git commit -m "Web Scraping CBE"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

Everything up-to-date


## Part 2 — Scraping Reviews

In [94]:
# Step 2: Scrape reviews
print(f"Scraping reviews for CBE Bank...")

result, continuation_token = reviews(
    CBE_APP_ID,
    lang='en',
    country='et',
    sort=Sort.NEWEST,
    count=400,
    filter_score_with=None
)

print(f"Collected {len(result)} raw reviews")

Scraping reviews for CBE Bank...
Collected 400 raw reviews

In [95]:
print("Keys in a single review:")
print(list(result[0].keys()))

print("\nFirst raw review (sample):")
for key, value in result[0].items():
    print(f"  {key}: {value}")

Keys in a single review:
['reviewId', 'userName', 'userImage', 'content', 'score', 'thumbsUpCount', 'reviewCreatedVersion', 'at', 'replyContent', 'repliedAt', 'appVersion']

First raw review (sample):
  reviewId: 79aecee0-a711-4a4a-96bd-e9836c4afd12
  userName: Mohamed Bushras
  userImage: https://play-lh.googleusercontent.com/a-/ALV-UjXclIxjFahviiSARPPjKTbHYioYt8Sq_0qJEalPQaijkMBU8_f4
  content: svabst keessatti argamu yoo ta'u yeroo ammaa kanas namoonni Finfinneerraa damee barnootaa isa keessatti argamu yoo ta'uu kan danda'u kan ujummoo Hala keessatti uummata Oromoo kan ujummoo dhiigaa ni jabeessa malee duuba akkan qabu natti kan ujummoo dhiigaa ni dabalu kan raawwatame yoo ta'u kan ujummoo dhiigaa ni jabeessa ta'e fudhachuuf ru kan ujummoo Hala app yoo ta'u kan akka hin taane kan akka baakteeriyaa irraa kan ujummoo Hala kan ujummoo dhiigaa ni
  score: 5
  thumbsUpCount: 0
  reviewCreatedVersion: 5.2.4
  at: 2026-05-18 01:12:03
  replyContent: None
  repliedAt: None
  appVersion: 5.2.4

In [96]:
raw_data = []

for r in result:
    raw_data.append({
        'review_id': r.get('reviewId', ''),
        'review'   : r.get('content', ''),
        'rating'   : r.get('score', None),
        'date'     : r.get('at', None),
        'bank'     : 'CBE Bank',
        'source'   : 'Google Play'
    })

# Build a DataFrame
df_raw = pd.DataFrame(raw_data)

print(f"Shape: {df_raw.shape}")
df_raw.head()

Shape: (400, 6)

,review_id,review,rating,date,bank,source
0,79aecee0-a711-4a4a-96bd-e9836c4afd12,svabst keessatti argamu yoo ta'u yeroo ammaa k...,5,2026-05-18 01:12:03,CBE Bank,Google Play
1,72fd0808-c8f7-435a-8337-0308012763da,nays,5,2026-05-17 18:46:14,CBE Bank,Google Play
2,67f82d81-ca79-46d0-a53b-e610fbce7950,very very good 👍 thanks commercial bank of eth...,5,2026-05-17 17:03:51,CBE Bank,Google Play
3,ea74fee5-c653-4e1c-8a5e-bad7f2299634,so nice,5,2026-05-17 16:12:24,CBE Bank,Google Play
4,b935e67f-b51d-4bd9-bc10-9cbd23531770,fantastic,5,2026-05-17 15:55:05,CBE Bank,Google Play

In [16]:
!git add .
!git commit -m "Scraping Reviews CBE"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

Everything up-to-date


## Part 3 — Exploring the Raw Data

In [97]:
print(f"Total reviews collected: {len(df_raw)}")
print(f"\nColumn dtypes:")
print(df_raw.dtypes)

Total reviews collected: 400

Column dtypes:
review_id               str
review                  str
rating                int64
date         datetime64[us]
bank                    str
source                  str
dtype: object

In [98]:
print("Rating distribution:")
rating_counts = df_raw['rating'].value_counts().sort_index(ascending=False)
for rating, count in rating_counts.items():
    bar = '█' * (count // 5)
    print(f"  {int(rating)} stars: {count:>4}  {bar}")

Rating distribution:
  5 stars:  275  ███████████████████████████████████████████████████████
  4 stars:   30  ██████
  3 stars:   25  █████
  2 stars:    9  █
  1 stars:   61  ████████████

In [99]:
print("Sample date values (raw):")
print(df_raw['date'].head(10).to_string())

print(f"\nDate dtype: {df_raw['date'].dtype}")

Sample date values (raw):
0   2026-05-18 01:12:03
1   2026-05-17 18:46:14
2   2026-05-17 17:03:51
3   2026-05-17 16:12:24
4   2026-05-17 15:55:05
5   2026-05-17 14:33:09
6   2026-05-17 13:23:30
7   2026-05-17 13:10:51
8   2026-05-17 09:25:49
9   2026-05-17 04:11:07

Date dtype: datetime64[us]

In [20]:
!git add .
!git commit -m "Exploring the Raw Data CBE"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

Everything up-to-date


## Part 4 — Data Quality Audit

In [100]:
print("=" * 50)
print("DATA QUALITY AUDIT")
print("=" * 50)

# --- Problem 1: Missing Values ---
print("\nProblem 1: Missing Values")
print("-" * 30)
missing = df_raw.isnull().sum()
missing_pct = (missing / len(df_raw) * 100).round(2)

for col in df_raw.columns:
    status = f"{missing[col]} missing ({missing_pct[col]}%)" if missing[col] > 0 else "OK"
    print(f"  {col:<15}: {status}")

==================================================
DATA QUALITY AUDIT
==================================================

Problem 1: Missing Values
------------------------------
  review_id      : OK
  review         : OK
  rating         : OK
  date           : OK
  bank           : OK
  source         : OK

In [101]:
print("Problem 2: Duplicates")
print("-" * 30)

# Exact duplicates on review text
exact_dupes = df_raw.duplicated(subset=['review']).sum()
print(f"  Exact duplicate reviews : {exact_dupes}")

# Duplicate review IDs
id_dupes = df_raw.duplicated(subset=['review_id']).sum()
print(f"  Duplicate review IDs    : {id_dupes}")

# Empty reviews (also a form of bad data)
empty_reviews = (df_raw['review'].str.strip() == '').sum()
print(f"  Empty review texts      : {empty_reviews}")

Problem 2: Duplicates
------------------------------
  Exact duplicate reviews : 103
  Duplicate review IDs    : 0
  Empty review texts      : 0

In [102]:
# --- Problem 3: Date Format ---
print("Problem 3: Date Format")
print("-" * 30)
print(f"  Current dtype: {df_raw['date'].dtype}")
print(f"  Sample values: {df_raw['date'].iloc[0]}")
print(f"  Target format: YYYY-MM-DD (string or date object)")

Problem 3: Date Format
------------------------------
  Current dtype: datetime64[us]
  Sample values: 2026-05-18 01:12:03
  Target format: YYYY-MM-DD (string or date object)

In [24]:
!git add .
!git commit -m "Data Quality Audit CBE"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

Everything up-to-date


## Part 5 — Cleaning Strategy

In [103]:
df = df_raw.copy()

print(f"Starting with: {len(df)} reviews")

Starting with: 400 reviews

In [104]:
before = len(df)

# Drop rows missing the critical columns
critical_cols = ['review', 'rating']
df = df.dropna(subset=critical_cols)

removed = before - len(df)
print(f"Removed {removed} rows with missing critical data")
print(f"Remaining: {len(df)} reviews")

Removed 0 rows with missing critical data
Remaining: 400 reviews

In [105]:
before = len(df)

df = df.drop_duplicates(subset=['review_id'], keep='first')

removed = before - len(df)
print(f"Removed {removed} duplicate reviews")
print(f"Remaining: {len(df)} reviews")

Removed 0 duplicate reviews
Remaining: 400 reviews

In [106]:
print("Before normalization:")
print(df['date'].head(3).to_string())
print(f"dtype: {df['date'].dtype}")

# Convert to pandas datetime, then format as YYYY-MM-DD string
df['date'] = pd.to_datetime(df['date']).dt.strftime('%Y-%m-%d')

print("\nAfter normalization:")
print(df['date'].head(3).to_string())
print(f"dtype: {df['date'].dtype}")

print(f"\nDate range: {df['date'].min()} to {df['date'].max()}")

Before normalization:
0   2026-05-18 01:12:03
1   2026-05-17 18:46:14
2   2026-05-17 17:03:51
dtype: datetime64[us]

After normalization:
0    2026-05-18
1    2026-05-17
2    2026-05-17
dtype: str

Date range: 2026-03-25 to 2026-05-18

In [107]:
def clean_text(text):
    """Standardize review text: collapse whitespace, strip edges."""
    if pd.isna(text):
        return ''
    text = str(text)
    text = re.sub(r'\s+', ' ', text)  # collapse multiple spaces/newlines
    text = text.strip()               # remove leading/trailing whitespace
    return text

# Show before/after on a sample review
sample_raw = "  Great   app!\n\nVery useful.  "
print(f"Before: {repr(sample_raw)}")
print(f"After : {repr(clean_text(sample_raw))}")

# Apply to the full column
df['review'] = df['review'].apply(clean_text)

# Remove any reviews that became empty after cleaning
before = len(df)
df = df[df['review'].str.len() > 0]
removed = before - len(df)
print(f"\nRemoved {removed} reviews that were empty after cleaning")

Before: '  Great   app!\n\nVery useful.  '
After : 'Great app! Very useful.'

Removed 0 reviews that were empty after cleaning

In [108]:
# Check for out-of-range ratings
invalid_ratings = df[(df['rating'] < 1) | (df['rating'] > 5)]
print(f"Invalid ratings (outside 1–5): {len(invalid_ratings)}")

# Remove them
df = df[(df['rating'] >= 1) & (df['rating'] <= 5)]

# Ensure rating is stored as integer
df['rating'] = df['rating'].astype(int)

print(f"Remaining: {len(df)} reviews")
print(f"Rating dtype: {df['rating'].dtype}")

Invalid ratings (outside 1–5): 0
Remaining: 400 reviews
Rating dtype: int64

In [31]:
!git add .
!git commit -m "Cleaning Strategy CBE"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

Everything up-to-date


## Part 6 — Final Output

In [109]:
# Select only the 5 required columns in the right order
df_clean = df[['review', 'rating', 'date', 'bank', 'source']].copy()

# Sort by date (newest first) for clean presentation
df_clean = df_clean.sort_values('date', ascending=False).reset_index(drop=True)

print(f"Final dataset shape: {df_clean.shape}")
df_clean.head(10)

Final dataset shape: (400, 5)

,review,rating,date,bank,source
0,svabst keessatti argamu yoo ta'u yeroo ammaa k...,5,2026-05-18,CBE Bank,Google Play
1,very very good 👍 thanks commercial bank of eth...,5,2026-05-17,CBE Bank,Google Play
2,so nice,5,2026-05-17,CBE Bank,Google Play
3,fantastic,5,2026-05-17,CBE Bank,Google Play
4,very nice,5,2026-05-17,CBE Bank,Google Play
5,f*k,1,2026-05-17,CBE Bank,Google Play
6,The Bank You can Always Rely on!,5,2026-05-17,CBE Bank,Google Play
7,Please make the CBE Noor toggle to be optional...,2,2026-05-17,CBE Bank,Google Play
8,Amazing App,5,2026-05-17,CBE Bank,Google Play
9,nays,5,2026-05-17,CBE Bank,Google Play

In [110]:
# Save to CSV
import os

# Create the directory safely
os.makedirs('data/raw', exist_ok=True)

# Define path using os.path.join for better compatibility
output_path = os.path.join('data', 'raw', 'CBE_bank_reviews_clean.csv')

df_clean.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")

Saved to: data\raw\CBE_bank_reviews_clean.csv

In [111]:
import pandas as pd
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
# Ensure NLTK vader_lexicon is downloaded
try:
    nltk.data.find('sentiment/vader_lexicon.zip')
except LookupError: # Correctly catch LookupError when resource is not found
    nltk.download('vader_lexicon')

analyzer = SentimentIntensityAnalyzer()

# Add 'month' column to df
df['month'] = pd.to_datetime(df['date']).dt.strftime('%B')

# Add 'length' column to df
df['length'] = df['review'].str.len()

# Add 'sentiment' column based on VADER compound scores to df
df['compound_score'] = df['review'].apply(lambda x: analyzer.polarity_scores(x)['compound'])
df['sentiment'] = df['compound_score'].apply(
    lambda score: 'Positive' if score >= 0.05 else ('Negative' if score <= -0.05 else 'Neutral')
)

# Select the desired columns in the right order to create df_clean
df_clean = df[['review', 'rating', 'date', 'bank', 'source', 'month', 'length', 'sentiment']].copy()

# Sort by date (newest first) for clean presentation
df_clean = df_clean.sort_values('date', ascending=False).reset_index(drop=True)

print(f"Final dataset shape: {df_clean.shape}")
df_clean.head(10)

Final dataset shape: (400, 8)

,review,rating,date,bank,source,month,length,sentiment
0,svabst keessatti argamu yoo ta'u yeroo ammaa k...,5,2026-05-18,CBE Bank,Google Play,May,457,Neutral
1,very very good 👍 thanks commercial bank of eth...,5,2026-05-17,CBE Bank,Google Play,May,55,Positive
2,so nice,5,2026-05-17,CBE Bank,Google Play,May,7,Positive
3,fantastic,5,2026-05-17,CBE Bank,Google Play,May,9,Positive
4,very nice,5,2026-05-17,CBE Bank,Google Play,May,9,Positive
5,f*k,1,2026-05-17,CBE Bank,Google Play,May,3,Neutral
6,The Bank You can Always Rely on!,5,2026-05-17,CBE Bank,Google Play,May,32,Neutral
7,Please make the CBE Noor toggle to be optional...,2,2026-05-17,CBE Bank,Google Play,May,280,Negative
8,Amazing App,5,2026-05-17,CBE Bank,Google Play,May,11,Positive
9,nays,5,2026-05-17,CBE Bank,Google Play,May,4,Neutral

In [112]:
# Save to CSV
import os

# Create the directory safely
os.makedirs('data/raw', exist_ok=True)

# Define path using os.path.join for better compatibility
output_path = os.path.join('data', 'raw', 'CBE_bank_reviews_clean_F.csv')

df_clean.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")

Saved to: data\raw\CBE_bank_reviews_clean_F.csv

In [34]:
!git add .
!git commit -m "Final Output CBE"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

Everything up-to-date


## Part 7 — Preprocessing Report

In [35]:
print("=" * 55)
print("  PREPROCESSING REPORT — CBE Bank Reviews")
print("=" * 55)

original_count = len(df_raw)
final_count    = len(df_clean)
removed_total  = original_count - final_count
retention_rate = (final_count / original_count * 100)

print(f"\n  Raw reviews collected  : {original_count:>6}")
print(f"  Reviews after cleaning : {final_count:>6}")
print(f"  Reviews removed        : {removed_total:>6}")
print(f"  Data retention rate    : {retention_rate:>5.1f}%")

quality = "EXCELLENT" if retention_rate >= 95 else ("GOOD" if retention_rate >= 90 else "NEEDS ATTENTION")
print(f"  Data quality           : {quality}")

print(f"\n  Date range : {df_clean['date'].min()}  to  {df_clean['date'].max()}")

print("\n  Rating distribution:")
for rating in sorted(df_clean['rating'].unique(), reverse=True):
    count = (df_clean['rating'] == rating).sum()
    pct   = count / final_count * 100
    bar   = '█' * (count // 5)
    print(f"    {rating} stars : {count:>4} ({pct:4.1f}%)  {bar}")

print("\n  Text length stats:")
lengths = df_clean['review'].str.len()
print(f"    Min    : {lengths.min()} characters")
print(f"    Median : {lengths.median():.0f} characters")
print(f"    Max    : {lengths.max()} characters")

print("\n  Columns in final CSV:")
for col in df_clean.columns:
    print(f"    - {col}")

print("\n" + "=" * 55)

=======================================================
  PREPROCESSING REPORT — CBE Bank Reviews
=======================================================

  Raw reviews collected  :    400
  Reviews after cleaning :    400
  Reviews removed        :      0
  Data retention rate    : 100.0%
  Data quality           : EXCELLENT

  Date range : 2026-03-25  to  2026-05-18

  Rating distribution:
    5 stars :  275 (68.8%)  ███████████████████████████████████████████████████████
    4 stars :   30 ( 7.5%)  ██████
    3 stars :   25 ( 6.2%)  █████
    2 stars :    9 ( 2.2%)  █
    1 stars :   61 (15.2%)  ████████████

  Text length stats:
    Min    : 1 characters
    Median : 13 characters
    Max    : 482 characters

  Columns in final CSV:
    - review
    - rating
    - date
    - bank
    - source

=======================================================

**DASHEN**


## Part 1 — Web Scraping

In [113]:
# The unique identifier for  DASHEN Bank's app on the Google Play Store
Dashen_APP_ID = "com.dashen.dashensuperapp"

# Step 1: Get app metadata (rating, installs, description...)
app_info = app(
    Dashen_APP_ID,
    lang='en',    # Language: English
    country='et'  # Country: Ethiopia
)

print("=" * 50)
print("DASHEN Bank App Info")
print("=" * 50)
print(f"App Title   : {app_info['title']}")
print(f"Current Score: {app_info['score']}")
print(f"Total Ratings: {app_info['ratings']:,}")
print(f"Total Reviews: {app_info['reviews']:,}")
print(f"Installs     : {app_info['installs']}")

==================================================
DASHEN Bank App Info
==================================================
App Title   : Dashen Bank
Current Score: 4.2528734
Total Ratings: 5,695
Total Reviews: 1,028
Installs     : 1,000,000+

In [37]:
!git add .
!git commit -m "Web Scraping DASHEN"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

Everything up-to-date


## Part 2 — Scraping Reviews

In [114]:
# Step 2: Scrape reviews
print(f"Scraping reviews for DASHEN Bank...")

result, continuation_token = reviews(
    Dashen_APP_ID,
    lang='en',
    country='et',
    sort=Sort.NEWEST,       # Most recent first
    count=400,              # Ask for more than 400 to be safe
    filter_score_with=None  # All star ratings
)

print(f"Collected {len(result)} raw reviews")

Scraping reviews for DASHEN Bank...
Collected 400 raw reviews

In [115]:
print("Keys in a single review:")
print(list(result[0].keys()))

print("\nFirst raw review (sample):")
for key, value in result[0].items():
    print(f"  {key}: {value}")

Keys in a single review:
['reviewId', 'userName', 'userImage', 'content', 'score', 'thumbsUpCount', 'reviewCreatedVersion', 'at', 'replyContent', 'repliedAt', 'appVersion']

First raw review (sample):
  reviewId: 0fc2de51-e53c-4eea-9db3-66bdb13121e0
  userName: gebreyohans hagos
  userImage: https://play-lh.googleusercontent.com/a/ACg8ocK-nSLgELmiolMtJ1dAKDUkKXJ6u_SyQegWjtqhlsKGNxXeAQ=mo
  content: It is a very cool application, but it requires a lot of network data. It also asks for updates too quickly, and it is not very familiar (user-friendly). It would be good if an Amharic option was included for the USSD menu
  score: 4
  thumbsUpCount: 0
  reviewCreatedVersion: None
  at: 2026-05-17 18:12:31
  replyContent: None
  repliedAt: None
  appVersion: None

In [116]:
raw_data = []

for r in result:
    raw_data.append({
        'review_id': r.get('reviewId', ''),
        'review'   : r.get('content', ''),
        'rating'   : r.get('score', None),
        'date'     : r.get('at', None),
        'bank'     : 'Dashen Bank',
        'source'   : 'Google Play'
    })

# Build a DataFrame
df_raw = pd.DataFrame(raw_data)

print(f"Shape: {df_raw.shape}")
df_raw.head()

Shape: (400, 6)

,review_id,review,rating,date,bank,source
0,0fc2de51-e53c-4eea-9db3-66bdb13121e0,"It is a very cool application, but it requires...",4,2026-05-17 18:12:31,Dashen Bank,Google Play
1,e12c0c30-3995-4ad2-b5d1-8c61b519ce76,excellent,5,2026-05-17 16:55:52,Dashen Bank,Google Play
2,e4c18ede-7a95-48c9-b0f8-0db83fe26191,Misguiding - Claimed anyone can convert ETB to...,1,2026-05-16 20:55:36,Dashen Bank,Google Play
3,6ccb8bab-6a2a-4048-8bf3-ea266459491e,good,5,2026-05-16 17:57:10,Dashen Bank,Google Play
4,12ebd51a-7912-464b-a81b-14a0aac358da,ok,5,2026-05-15 20:41:19,Dashen Bank,Google Play

In [41]:
!git add .
!git commit -m "Scraping Reviews DASHEN"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

Everything up-to-date


## Part 3 — Exploring the Raw Data

In [117]:
# Basic shape and types
print(f"Total reviews collected: {len(df_raw)}")
print(f"\nColumn dtypes:")
print(df_raw.dtypes)

Total reviews collected: 400

Column dtypes:
review_id               str
review                  str
rating                int64
date         datetime64[us]
bank                    str
source                  str
dtype: object

In [118]:
print("Rating distribution:")
rating_counts = df_raw['rating'].value_counts().sort_index(ascending=False)
for rating, count in rating_counts.items():
    bar = '█' * (count // 5)
    print(f"  {int(rating)} stars: {count:>4}  {bar}")

Rating distribution:
  5 stars:  267  █████████████████████████████████████████████████████
  4 stars:   27  █████
  3 stars:   19  ███
  2 stars:   11  ██
  1 stars:   76  ███████████████

In [119]:
print("Sample date values (raw):")
print(df_raw['date'].head(10).to_string())

print(f"\nDate dtype: {df_raw['date'].dtype}")

Sample date values (raw):
0   2026-05-17 18:12:31
1   2026-05-17 16:55:52
2   2026-05-16 20:55:36
3   2026-05-16 17:57:10
4   2026-05-15 20:41:19
5   2026-05-15 18:33:32
6   2026-05-14 19:33:42
7   2026-05-14 19:26:20
8   2026-05-14 17:35:20
9   2026-05-14 17:29:26

Date dtype: datetime64[us]

In [45]:
!git add .
!git commit -m "Exploring the Raw Data DASHEN"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

Everything up-to-date


## Part 4 — Data Quality Audit

In [120]:
print("=" * 50)
print("DATA QUALITY AUDIT")
print("=" * 50)

# --- Problem 1: Missing Values ---
print("\nProblem 1: Missing Values")
print("-" * 30)
missing = df_raw.isnull().sum()
missing_pct = (missing / len(df_raw) * 100).round(2)

for col in df_raw.columns:
    status = f"{missing[col]} missing ({missing_pct[col]}%)" if missing[col] > 0 else "OK"
    print(f"  {col:<15}: {status}")

==================================================
DATA QUALITY AUDIT
==================================================

Problem 1: Missing Values
------------------------------
  review_id      : OK
  review         : OK
  rating         : OK
  date           : OK
  bank           : OK
  source         : OK

In [121]:
# --- Problem 2: Duplicate Reviews ---
print("Problem 2: Duplicates")
print("-" * 30)

# Exact duplicates on review text
exact_dupes = df_raw.duplicated(subset=['review']).sum()
print(f"  Exact duplicate reviews : {exact_dupes}")

# Duplicate review IDs
id_dupes = df_raw.duplicated(subset=['review_id']).sum()
print(f"  Duplicate review IDs    : {id_dupes}")

# Empty reviews (also a form of bad data)
empty_reviews = (df_raw['review'].str.strip() == '').sum()
print(f"  Empty review texts      : {empty_reviews}")

Problem 2: Duplicates
------------------------------
  Exact duplicate reviews : 60
  Duplicate review IDs    : 0
  Empty review texts      : 0

In [122]:
# --- Problem 3: Date Format ---
print("Problem 3: Date Format")
print("-" * 30)
print(f"  Current dtype: {df_raw['date'].dtype}")
print(f"  Sample values: {df_raw['date'].iloc[0]}")
print(f"  Target format: YYYY-MM-DD (string or date object)")

Problem 3: Date Format
------------------------------
  Current dtype: datetime64[us]
  Sample values: 2026-05-17 18:12:31
  Target format: YYYY-MM-DD (string or date object)

In [49]:
!git add .
!git commit -m "Data Quality Audit DASHEN"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

Everything up-to-date


## Part 5 — Cleaning Strategy

In [123]:
df = df_raw.copy()

print(f"Starting with: {len(df)} reviews")

Starting with: 400 reviews

In [124]:
before = len(df)

# Drop rows missing the critical columns
critical_cols = ['review', 'rating']
df = df.dropna(subset=critical_cols)

removed = before - len(df)
print(f"Removed {removed} rows with missing critical data")
print(f"Remaining: {len(df)} reviews")

Removed 0 rows with missing critical data
Remaining: 400 reviews

In [125]:
before = len(df)

df = df.drop_duplicates(subset=['review_id'], keep='first')

removed = before - len(df)
print(f"Removed {removed} duplicate reviews")
print(f"Remaining: {len(df)} reviews")

Removed 0 duplicate reviews
Remaining: 400 reviews

In [126]:
print("Before normalization:")
print(df['date'].head(3).to_string())
print(f"dtype: {df['date'].dtype}")

# Convert to pandas datetime, then format as YYYY-MM-DD string
df['date'] = pd.to_datetime(df['date']).dt.strftime('%Y-%m-%d')

print("\nAfter normalization:")
print(df['date'].head(3).to_string())
print(f"dtype: {df['date'].dtype}")

print(f"\nDate range: {df['date'].min()} to {df['date'].max()}")

Before normalization:
0   2026-05-17 18:12:31
1   2026-05-17 16:55:52
2   2026-05-16 20:55:36
dtype: datetime64[us]

After normalization:
0    2026-05-17
1    2026-05-17
2    2026-05-16
dtype: str

Date range: 2025-10-01 to 2026-05-17

In [127]:
def clean_text(text):
    """Standardize review text: collapse whitespace, strip edges."""
    if pd.isna(text):
        return ''
    text = str(text)
    text = re.sub(r'\s+', ' ', text)  # collapse multiple spaces/newlines
    text = text.strip()               # remove leading/trailing whitespace
    return text

# Show before/after on a sample review
sample_raw = "  Great   app!\n\nVery useful.  "
print(f"Before: {repr(sample_raw)}")
print(f"After : {repr(clean_text(sample_raw))}")

# Apply to the full column
df['review'] = df['review'].apply(clean_text)

# Remove any reviews that became empty after cleaning
before = len(df)
df = df[df['review'].str.len() > 0]
removed = before - len(df)
print(f"\nRemoved {removed} reviews that were empty after cleaning")

Before: '  Great   app!\n\nVery useful.  '
After : 'Great app! Very useful.'

Removed 0 reviews that were empty after cleaning

In [128]:
# Check for out-of-range ratings
invalid_ratings = df[(df['rating'] < 1) | (df['rating'] > 5)]
print(f"Invalid ratings (outside 1–5): {len(invalid_ratings)}")

# Remove them
df = df[(df['rating'] >= 1) & (df['rating'] <= 5)]

# Ensure rating is stored as integer
df['rating'] = df['rating'].astype(int)

print(f"Remaining: {len(df)} reviews")
print(f"Rating dtype: {df['rating'].dtype}")

Invalid ratings (outside 1–5): 0
Remaining: 400 reviews
Rating dtype: int64

In [56]:
!git add .
!git commit -m "Cleaning Strategy DASHEN"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

Everything up-to-date


## Part 6 — Final Output

In [129]:
# Select only the 5 required columns in the right order
df_clean = df[['review', 'rating', 'date', 'bank', 'source']].copy()

# Sort by date (newest first) for clean presentation
df_clean = df_clean.sort_values('date', ascending=False).reset_index(drop=True)

print(f"Final dataset shape: {df_clean.shape}")
df_clean.head(10)

Final dataset shape: (400, 5)

,review,rating,date,bank,source
0,"It is a very cool application, but it requires...",4,2026-05-17,Dashen Bank,Google Play
1,excellent,5,2026-05-17,Dashen Bank,Google Play
2,Misguiding - Claimed anyone can convert ETB to...,1,2026-05-16,Dashen Bank,Google Play
3,good,5,2026-05-16,Dashen Bank,Google Play
4,ok,5,2026-05-15,Dashen Bank,Google Play
5,best app so far. thank you,5,2026-05-15,Dashen Bank,Google Play
6,Very Annoying App i tried to open virtual bank...,1,2026-05-14,Dashen Bank,Google Play
7,good,5,2026-05-14,Dashen Bank,Google Play
8,good,5,2026-05-14,Dashen Bank,Google Play
9,good app but it was doesnt work other bank tra...,5,2026-05-14,Dashen Bank,Google Play

In [130]:
# Save to CSV
import os
os.makedirs('data/raw', exist_ok=True)

output_path = 'data/raw/Dashen_bank_reviews_clean.csv'
df_clean.to_csv(output_path, index=False)

print(f"Saved to: {output_path}")

Saved to: data/raw/Dashen_bank_reviews_clean.csv

In [131]:
import pandas as pd
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
# Ensure NLTK vader_lexicon is downloaded
try:
    nltk.data.find('sentiment/vader_lexicon.zip')
except LookupError: # Correctly catch LookupError when resource is not found
    nltk.download('vader_lexicon')

analyzer = SentimentIntensityAnalyzer()

# Add 'month' column to df
df['month'] = pd.to_datetime(df['date']).dt.strftime('%B')

# Add 'length' column to df
df['length'] = df['review'].str.len()

# Add 'sentiment' column based on VADER compound scores to df
df['compound_score'] = df['review'].apply(lambda x: analyzer.polarity_scores(x)['compound'])
df['sentiment'] = df['compound_score'].apply(
    lambda score: 'Positive' if score >= 0.05 else ('Negative' if score <= -0.05 else 'Neutral')
)

# Select the desired columns in the right order to create df_clean
df_clean = df[['review', 'rating', 'date', 'bank', 'source', 'month', 'length', 'sentiment']].copy()

# Sort by date (newest first) for clean presentation
df_clean = df_clean.sort_values('date', ascending=False).reset_index(drop=True)

print(f"Final dataset shape: {df_clean.shape}")
df_clean.head(10)

Final dataset shape: (400, 8)

,review,rating,date,bank,source,month,length,sentiment
0,"It is a very cool application, but it requires...",4,2026-05-17,Dashen Bank,Google Play,May,221,Positive
1,excellent,5,2026-05-17,Dashen Bank,Google Play,May,9,Positive
2,Misguiding - Claimed anyone can convert ETB to...,1,2026-05-16,Dashen Bank,Google Play,May,85,Negative
3,good,5,2026-05-16,Dashen Bank,Google Play,May,4,Positive
4,ok,5,2026-05-15,Dashen Bank,Google Play,May,2,Positive
5,best app so far. thank you,5,2026-05-15,Dashen Bank,Google Play,May,26,Positive
6,Very Annoying App i tried to open virtual bank...,1,2026-05-14,Dashen Bank,Google Play,May,207,Negative
7,good,5,2026-05-14,Dashen Bank,Google Play,May,4,Positive
8,good,5,2026-05-14,Dashen Bank,Google Play,May,4,Positive
9,good app but it was doesnt work other bank tra...,5,2026-05-14,Dashen Bank,Google Play,May,83,Positive

In [132]:
import os
os.makedirs('data/raw', exist_ok=True)

output_path = 'data/raw/Dashen_bank_reviews_clean_F.csv'
df_clean.to_csv(output_path, index=False)

print(f"Saved to: {output_path}")

Saved to: data/raw/Dashen_bank_reviews_clean_F.csv

In [59]:
!git add .
!git commit -m "Final Output"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

Everything up-to-date


## Part 7 — Preprocessing Report

In [60]:
print("=" * 55)
print("  PREPROCESSING REPORT — Dashen Bank Reviews")
print("=" * 55)

original_count = len(df_raw)
final_count    = len(df_clean)
removed_total  = original_count - final_count
retention_rate = (final_count / original_count * 100)

print(f"\n  Raw reviews collected  : {original_count:>6}")
print(f"  Reviews after cleaning : {final_count:>6}")
print(f"  Reviews removed        : {removed_total:>6}")
print(f"  Data retention rate    : {retention_rate:>5.1f}%")

quality = "EXCELLENT" if retention_rate >= 95 else ("GOOD" if retention_rate >= 90 else "NEEDS ATTENTION")
print(f"  Data quality           : {quality}")

print(f"\n  Date range : {df_clean['date'].min()}  to  {df_clean['date'].max()}")

print("\n  Rating distribution:")
for rating in sorted(df_clean['rating'].unique(), reverse=True):
    count = (df_clean['rating'] == rating).sum()
    pct   = count / final_count * 100
    bar   = '█' * (count // 5)
    print(f"    {rating} stars : {count:>4} ({pct:4.1f}%)  {bar}")

print("\n  Text length stats:")
lengths = df_clean['review'].str.len()
print(f"    Min    : {lengths.min()} characters")
print(f"    Median : {lengths.median():.0f} characters")
print(f"    Max    : {lengths.max()} characters")

print("\n  Columns in final CSV:")
for col in df_clean.columns:
    print(f"    - {col}")

print("\n" + "=" * 55)

=======================================================
  PREPROCESSING REPORT — Dashen Bank Reviews
=======================================================

  Raw reviews collected  :    400
  Reviews after cleaning :    400
  Reviews removed        :      0
  Data retention rate    : 100.0%
  Data quality           : EXCELLENT

  Date range : 2025-10-01  to  2026-05-17

  Rating distribution:
    5 stars :  267 (66.8%)  █████████████████████████████████████████████████████
    4 stars :   27 ( 6.8%)  █████
    3 stars :   19 ( 4.8%)  ███
    2 stars :   11 ( 2.8%)  ██
    1 stars :   76 (19.0%)  ███████████████

  Text length stats:
    Min    : 1 characters
    Median : 22 characters
    Max    : 498 characters

  Columns in final CSV:
    - review
    - rating
    - date
    - bank
    - source

=======================================================

**BOA**


## Part 1 — Web Scraping

In [133]:
# The unique identifier for BOA Bank's app on the Google Play Store
BOA_APP_ID = "com.boa.boaMobileBanking"

# Step 1: Get app metadata (rating, installs, description...)
app_info = app(
    BOA_APP_ID,
    lang='en',    # Language: English
    country='et'  # Country: Ethiopia
)

print("=" * 50)
print(" BOA Bank App Info")
print("=" * 50)
print(f"App Title   : {app_info['title']}")
print(f"Current Score: {app_info['score']}")
print(f"Total Ratings: {app_info['ratings']:,}")
print(f"Total Reviews: {app_info['reviews']:,}")
print(f"Installs     : {app_info['installs']}")

==================================================
 BOA Bank App Info
==================================================
App Title   : BoA Mobile
Current Score: 4.3961663
Total Ratings: 9,294
Total Reviews: 1,469
Installs     : 1,000,000+

In [62]:
!git add .
!git commit -m " Web Scraping BOA"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

Everything up-to-date


## Part 2 — Scraping Reviews

In [63]:
print(f"Scraping reviews for BOA Bank...")

result, continuation_token = reviews(
    BOA_APP_ID,
    lang='en',
    country='et',
    sort=Sort.NEWEST,       # Most recent first
    count=400,              # Ask for more than 400 to be safe
    filter_score_with=None  # All star ratings
)

Scraping reviews for BOA Bank...

In [64]:
print("Keys in a single review:")
print(list(result[0].keys()))

print("\nFirst raw review (sample):")
for key, value in result[0].items():
    print(f"  {key}: {value}")

Keys in a single review:
['reviewId', 'userName', 'userImage', 'content', 'score', 'thumbsUpCount', 'reviewCreatedVersion', 'at', 'replyContent', 'repliedAt', 'appVersion']

First raw review (sample):
  reviewId: ea419fbc-41fc-4211-b3b4-84e87d2952a4
  userName: Kalkidan Meskelu
  userImage: https://play-lh.googleusercontent.com/a-/ALV-UjWKtZmngrFb1kSulQi4ytAq52_iUfLtYwJxkTO0_Ja0lx4FJGs
  content: the transaction is not working???? fix it
  score: 1
  thumbsUpCount: 0
  reviewCreatedVersion: 26.05.11
  at: 2026-05-18 01:13:03
  replyContent: None
  repliedAt: None
  appVersion: 26.05.11

In [65]:
raw_data = []

for r in result:
    raw_data.append({
        'review_id': r.get('reviewId', ''),
        'review'   : r.get('content', ''),
        'rating'   : r.get('score', None),
        'date'     : r.get('at', None),
        'bank'     : 'BOA Bank',
        'source'   : 'Google Play'
    })

# Build a DataFrame
df_raw = pd.DataFrame(raw_data)

print(f"Shape: {df_raw.shape}")
df_raw.head()

Shape: (400, 6)

,review_id,review,rating,date,bank,source
0,ea419fbc-41fc-4211-b3b4-84e87d2952a4,the transaction is not working???? fix it,1,2026-05-18 01:13:03,BOA Bank,Google Play
1,0fe83567-9471-413c-b722-a24757bb5d82,sometimes The App Is not goibg through,3,2026-05-17 15:21:31,BOA Bank,Google Play
2,9dd3879e-2b0c-4058-8c8c-19f6b376f69c,"The worst app, also bank am begging for my own...",1,2026-05-16 12:35:22,BOA Bank,Google Play
3,5f69466d-ec06-4eb5-816c-296accffeff2,was Good 🙏,5,2026-05-16 00:10:06,BOA Bank,Google Play
4,f9246b8a-6688-4249-b804-0b0c5dd60590,cool,5,2026-05-15 21:07:21,BOA Bank,Google Play

In [66]:
!git add .
!git commit -m "Scraping Reviews BOA"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

Everything up-to-date


## Part 3 — Exploring the Raw Data

In [67]:
print(f"Total reviews collected: {len(df_raw)}")
print(f"\nColumn dtypes:")
print(df_raw.dtypes)

Total reviews collected: 400

Column dtypes:
review_id               str
review                  str
rating                int64
date         datetime64[us]
bank                    str
source                  str
dtype: object

In [68]:
print("Rating distribution:")
rating_counts = df_raw['rating'].value_counts().sort_index(ascending=False)
for rating, count in rating_counts.items():
    bar = '█' * (count // 5)
    print(f"  {int(rating)} stars: {count:>4}  {bar}")

Rating distribution:
  5 stars:  231  ██████████████████████████████████████████████
  4 stars:   32  ██████
  3 stars:   14  ██
  2 stars:   13  ██
  1 stars:  110  ██████████████████████

In [69]:
print("Sample date values (raw):")
print(df_raw['date'].head(10).to_string())

print(f"\nDate dtype: {df_raw['date'].dtype}")

Sample date values (raw):
0   2026-05-18 01:13:03
1   2026-05-17 15:21:31
2   2026-05-16 12:35:22
3   2026-05-16 00:10:06
4   2026-05-15 21:07:21
5   2026-05-15 15:01:09
6   2026-05-14 21:18:44
7   2026-05-12 11:50:32
8   2026-05-11 18:18:54
9   2026-05-09 14:41:50

Date dtype: datetime64[us]

In [70]:
!git add .
!git commit -m "Exploring the Raw Data BOA"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

Everything up-to-date


## Part 4 — Data Quality Audit

In [71]:
print("=" * 50)
print("DATA QUALITY AUDIT")
print("=" * 50)

# --- Problem 1: Missing Values ---
print("\nProblem 1: Missing Values")
print("-" * 30)
missing = df_raw.isnull().sum()
missing_pct = (missing / len(df_raw) * 100).round(2)

for col in df_raw.columns:
    status = f"{missing[col]} missing ({missing_pct[col]}%)" if missing[col] > 0 else "OK"
    print(f"  {col:<15}: {status}")

==================================================
DATA QUALITY AUDIT
==================================================

Problem 1: Missing Values
------------------------------
  review_id      : OK
  review         : OK
  rating         : OK
  date           : OK
  bank           : OK
  source         : OK

In [72]:
# --- Problem 2: Duplicate Reviews ---
print("Problem 2: Duplicates")
print("-" * 30)

# Exact duplicates on review text
exact_dupes = df_raw.duplicated(subset=['review']).sum()
print(f"  Exact duplicate reviews : {exact_dupes}")

# Duplicate review IDs
id_dupes = df_raw.duplicated(subset=['review_id']).sum()
print(f"  Duplicate review IDs    : {id_dupes}")

# Empty reviews (also a form of bad data)
empty_reviews = (df_raw['review'].str.strip() == '').sum()
print(f"  Empty review texts      : {empty_reviews}")

Problem 2: Duplicates
------------------------------
  Exact duplicate reviews : 66
  Duplicate review IDs    : 0
  Empty review texts      : 0

In [73]:

print("Problem 3: Date Format")
print("-" * 30)
print(f"  Current dtype: {df_raw['date'].dtype}")
print(f"  Sample values: {df_raw['date'].iloc[0]}")
print(f"  Target format: YYYY-MM-DD (string or date object)")

Problem 3: Date Format
------------------------------
  Current dtype: datetime64[us]
  Sample values: 2026-05-18 01:13:03
  Target format: YYYY-MM-DD (string or date object)

In [74]:
!git add .
!git commit -m "Data Quality Audit BOA"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

Everything up-to-date


## Part 5 — Cleaning Strategy

In [75]:
# Work on a copy so raw data stays untouched
df = df_raw.copy()

print(f"Starting with: {len(df)} reviews")

Starting with: 400 reviews

In [76]:
before = len(df)

# Drop rows missing the critical columns
critical_cols = ['review', 'rating']
df = df.dropna(subset=critical_cols)

removed = before - len(df)
print(f"Removed {removed} rows with missing critical data")
print(f"Remaining: {len(df)} reviews")

Removed 0 rows with missing critical data
Remaining: 400 reviews

In [77]:
before = len(df)

df = df.drop_duplicates(subset=['review_id'], keep='first')

removed = before - len(df)
print(f"Removed {removed} duplicate reviews")
print(f"Remaining: {len(df)} reviews")

Removed 0 duplicate reviews
Remaining: 400 reviews

In [78]:
print("Before normalization:")
print(df['date'].head(3).to_string())
print(f"dtype: {df['date'].dtype}")

# Convert to pandas datetime, then format as YYYY-MM-DD string
df['date'] = pd.to_datetime(df['date']).dt.strftime('%Y-%m-%d')

print("\nAfter normalization:")
print(df['date'].head(3).to_string())
print(f"dtype: {df['date'].dtype}")

print(f"\nDate range: {df['date'].min()} to {df['date'].max()}")

Before normalization:
0   2026-05-18 01:13:03
1   2026-05-17 15:21:31
2   2026-05-16 12:35:22
dtype: datetime64[us]

After normalization:
0    2026-05-18
1    2026-05-17
2    2026-05-16
dtype: str

Date range: 2025-06-21 to 2026-05-18

In [79]:
def clean_text(text):
    """Standardize review text: collapse whitespace, strip edges."""
    if pd.isna(text):
        return ''
    text = str(text)
    text = re.sub(r'\s+', ' ', text)  # collapse multiple spaces/newlines
    text = text.strip()               # remove leading/trailing whitespace
    return text

# Show before/after on a sample review
sample_raw = "  Great   app!\n\nVery useful.  "
print(f"Before: {repr(sample_raw)}")
print(f"After : {repr(clean_text(sample_raw))}")

# Apply to the full column
df['review'] = df['review'].apply(clean_text)

# Remove any reviews that became empty after cleaning
before = len(df)
df = df[df['review'].str.len() > 0]
removed = before - len(df)
print(f"\nRemoved {removed} reviews that were empty after cleaning")

Before: '  Great   app!\n\nVery useful.  '
After : 'Great app! Very useful.'

Removed 0 reviews that were empty after cleaning

In [80]:
# Check for out-of-range ratings
invalid_ratings = df[(df['rating'] < 1) | (df['rating'] > 5)]
print(f"Invalid ratings (outside 1–5): {len(invalid_ratings)}")

# Remove them
df = df[(df['rating'] >= 1) & (df['rating'] <= 5)]

# Ensure rating is stored as integer
df['rating'] = df['rating'].astype(int)

print(f"Remaining: {len(df)} reviews")
print(f"Rating dtype: {df['rating'].dtype}")

Invalid ratings (outside 1–5): 0
Remaining: 400 reviews
Rating dtype: int64

In [81]:
!git add .
!git commit -m "Cleaning Strategy BOA"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

Everything up-to-date


## Part 6 — Final Output

In [ ]:
# Select only the 5 required columns in the right order
df_clean = df[['review', 'rating', 'date', 'bank', 'source']].copy()

# Sort by date (newest first) for clean presentation
df_clean = df_clean.sort_values('date', ascending=False).reset_index(drop=True)

print(f"Final dataset shape: {df_clean.shape}")
df_clean.head(10)

Final dataset shape: (400, 5)

,review,rating,date,bank,source
0,the transaction is not working???? fix it,1,2026-05-18,BOA Bank,Google Play
1,sometimes The App Is not goibg through,3,2026-05-17,BOA Bank,Google Play
2,"The worst app, also bank am begging for my own...",1,2026-05-16,BOA Bank,Google Play
3,was Good 🙏,5,2026-05-16,BOA Bank,Google Play
4,cool,5,2026-05-15,BOA Bank,Google Play
5,Its Good,5,2026-05-15,BOA Bank,Google Play
6,good,5,2026-05-14,BOA Bank,Google Play
7,it's very good app,5,2026-05-12,BOA Bank,Google Play
8,this app is good but the speed of app is very ...,2,2026-05-11,BOA Bank,Google Play
9,good,5,2026-05-09,BOA Bank,Google Play

In [83]:
# Save to CSV
import os
os.makedirs('data/raw', exist_ok=True)

output_path = 'data/raw/BOA_bank_reviews_clean.csv'
df_clean.to_csv(output_path, index=False)

print(f"Saved to: {output_path}")

Saved to: data/raw/BOA_bank_reviews_clean.csv

In [90]:
import pandas as pd
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
# Ensure NLTK vader_lexicon is downloaded
try:
    nltk.data.find('sentiment/vader_lexicon.zip')
except LookupError: # Correctly catch LookupError when resource is not found
    nltk.download('vader_lexicon')

analyzer = SentimentIntensityAnalyzer()

# Add 'month' column to df
df['month'] = pd.to_datetime(df['date']).dt.strftime('%B')

# Add 'length' column to df
df['length'] = df['review'].str.len()

# Add 'sentiment' column based on VADER compound scores to df
df['compound_score'] = df['review'].apply(lambda x: analyzer.polarity_scores(x)['compound'])
df['sentiment'] = df['compound_score'].apply(
    lambda score: 'Positive' if score >= 0.05 else ('Negative' if score <= -0.05 else 'Neutral')
)

# Select the desired columns in the right order to create df_clean
df_clean = df[['review', 'rating', 'date', 'bank', 'source', 'month', 'length', 'sentiment']].copy()

# Sort by date (newest first) for clean presentation
df_clean = df_clean.sort_values('date', ascending=False).reset_index(drop=True)

print(f"Final dataset shape: {df_clean.shape}")
df_clean.head(10)

Final dataset shape: (400, 8)

,review,rating,date,bank,source,month,length,sentiment
0,the transaction is not working???? fix it,1,2026-05-18,BOA Bank,Google Play,May,41,Neutral
1,sometimes The App Is not goibg through,3,2026-05-17,BOA Bank,Google Play,May,38,Neutral
2,"The worst app, also bank am begging for my own...",1,2026-05-16,BOA Bank,Google Play,May,52,Negative
3,was Good 🙏,5,2026-05-16,BOA Bank,Google Play,May,10,Positive
4,cool,5,2026-05-15,BOA Bank,Google Play,May,4,Positive
5,Its Good,5,2026-05-15,BOA Bank,Google Play,May,8,Positive
6,good,5,2026-05-14,BOA Bank,Google Play,May,4,Positive
7,it's very good app,5,2026-05-12,BOA Bank,Google Play,May,18,Positive
8,this app is good but the speed of app is very ...,2,2026-05-11,BOA Bank,Google Play,May,50,Positive
9,good,5,2026-05-09,BOA Bank,Google Play,May,4,Positive

In [91]:
# Save to CSV
import os
os.makedirs('data/raw', exist_ok=True)

output_path = 'data/raw/BOA_bank_reviews_clean_F.csv'
df_clean.to_csv(output_path, index=False)

print(f"Saved to: {output_path}")

Saved to: data/raw/BOA_bank_reviews_clean_F.csv

In [84]:
!git add .
!git commit -m "Final Output BOA"
!git push https://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@github.com/edent4313-star/fintech-review-analytics.git Task-1

On branch Task-1
Your branch is up to date with 'origin/Task-1'.

nothing to commit, working tree clean

Everything up-to-date


## Part 7 — Preprocessing Report

In [85]:
print("=" * 55)
print("  PREPROCESSING REPORT — BOA Bank Reviews")
print("=" * 55)

original_count = len(df_raw)
final_count    = len(df_clean)
removed_total  = original_count - final_count
retention_rate = (final_count / original_count * 100)

print(f"\n  Raw reviews collected  : {original_count:>6}")
print(f"  Reviews after cleaning : {final_count:>6}")
print(f"  Reviews removed        : {removed_total:>6}")
print(f"  Data retention rate    : {retention_rate:>5.1f}%")

quality = "EXCELLENT" if retention_rate >= 95 else ("GOOD" if retention_rate >= 90 else "NEEDS ATTENTION")
print(f"  Data quality           : {quality}")

print(f"\n  Date range : {df_clean['date'].min()}  to  {df_clean['date'].max()}")

print("\n  Rating distribution:")
for rating in sorted(df_clean['rating'].unique(), reverse=True):
    count = (df_clean['rating'] == rating).sum()
    pct   = count / final_count * 100
    bar   = '█' * (count // 5)
    print(f"    {rating} stars : {count:>4} ({pct:4.1f}%)  {bar}")

print("\n  Text length stats:")
lengths = df_clean['review'].str.len()
print(f"    Min    : {lengths.min()} characters")
print(f"    Median : {lengths.median():.0f} characters")
print(f"    Max    : {lengths.max()} characters")

print("\n  Columns in final CSV:")
for col in df_clean.columns:
    print(f"    - {col}")

print("\n" + "=" * 55)

=======================================================
  PREPROCESSING REPORT — BOA Bank Reviews
=======================================================

  Raw reviews collected  :    400
  Reviews after cleaning :    400
  Reviews removed        :      0
  Data retention rate    : 100.0%
  Data quality           : EXCELLENT

  Date range : 2025-06-21  to  2026-05-18

  Rating distribution:
    5 stars :  231 (57.8%)  ██████████████████████████████████████████████
    4 stars :   32 ( 8.0%)  ██████
    3 stars :   14 ( 3.5%)  ██
    2 stars :   13 ( 3.2%)  ██
    1 stars :  110 (27.5%)  ██████████████████████

  Text length stats:
    Min    : 1 characters
    Median : 14 characters
    Max    : 492 characters

  Columns in final CSV:
    - review
    - rating
    - date
    - bank
    - source

=======================================================